Repository CanonicalLtd/maas-docs, pull requests merged in 2018-02, with the labels that each got.

#763 Updated installconfig-upgrade-postgres.md
  en/installconfig-install.md
  en/installconfig-upgrade-postgres.md
  en/metadata.yaml
Labels: devel

#773 Updated default install to snap
  en/index.md
  en/installconfig-checklist.md
  en/installconfig-install.md
  en/installconfig-snap-install.md
  en/installconfig-webui.md
  en/intro-explore.md
  en/metadata.yaml
Labels: devel

#772 Audit Event Logs update
  en/manage-audit-events.md
  en/metadata.yaml
Labels: devel

#774 Backport #772 to devel
  en/manage-audit-events.md
  en/metadata.yaml
Labels: doc-utils

#775 Backport #773 to devel
  en/index.md
  en/installconfig-checklist.md
  en/installconfig-install.md
  en/installconfig-snap-install.md
  en/installconfig-webui.md
  en/intro-explore.md
  en/metadata.yaml
Labels: doc-utils

#767 Add Firmware Update and Configure HBA Docs
  en/nodes-hw-scripts-fields.md
  en/nodes-hw-scripts.md
  en/nodes-scripts.md
Labels: 2.3, devel

#782 Backport #778 to 2.3
  .travis.yml
Labels: doc-utils

#783 Backport #778 to 2.2
  .travis.yml
Labels: doc-utils

#780 Add webui document to the toc.
  en/metadata.yaml
Labels: devel

#788 Backport #787 to devel
  en/nodes-tags.md
Labels: doc-utils

#789 Backport #787 to 2.3
  en/nodes-tags.md
Labels: doc-utils

#790 Backport #787 to 2.2
  en/nodes-tags.md
Labels: doc-utils

#791 Backport #780 to devel
  en/metadata.yaml
Labels: doc-utils

#793 New contact-us page
  en/contact-us.md
  en/metadata.yaml
Labels: 1.9, 2.0, 2.1, 2.2, 2.3, api, devel

#794 Backport #793 to devel
  en/contact-us.md
  en/metadata.yaml
Labels: doc-utils
